### ISSUE TITLE
Problem adding Sub-Devices

### ISSUE THREAD

**Issue by leofuscaldi** [leeyuentuen/localtuya#61]
Hi,

i came across following the trails left for the problem "Localtuya with Zigbee devices". My gateway is v3.4 so I had to go with your beta versions of 3.7 to add it and try to add sub-devices. I installed 3.7beta2 and managed to add my Zigbee Gateway. That was as far as I could get. Then I went for the last version available at moment, beta10, moved back to beta9... and in all I got the same problem when adding the sub-devices:
1 - I add a localtuya
2 - choose (sub-device)
3 - It shows a screen with the Parent Gateway selected. I put a name and the device ID. Didn't figure out yet what is this hw_version or where to get it. Even tried writing 3.3 and 3.4 but the outcome is the same: on the next screen, goes to Add Data Point saying that the detection failed and asking for a number.

How should I proceed now?

Have a large number of devices such as Light Switches (modules), Thermostat valves, Sensors (Temp/Hum, Water leak), and also some bluetooth devices, which I'd like to make their way to the localtuya platform and to my HA.

Thanks in advance

**Comment by alexualbu** [comment]
@leofuscaldi , you should use at least beta9 - then the only thing you need to add the sub-device is the cid: in the developer console (the site you used) go to Cloud/api explorer and use the Device information api where you enter your device id. From here grab the node_id
![image](https://user-images.githubusercontent.com/48317290/233765211-bcb601ee-b138-40af-af09-9d2a669a69b0.png)

**Comment by leofuscaldi** [comment]
Dear @alexualbu, indeed, it worked as you instructed, I could add all my zigbee devices. But some didn't work,

For the light switch modules modules, I have the ID's 1, 7 and 14 only and none of them Switches the light on/off, they just get the status of the light.

The water leak sensor, according what I found on tuya site, should have 3 entries, but only the one for the battery is being recognized.

The same with the Bluetooth Fingerbot, only have the value for the battery level.

All other worked. 

Can I help anyhow with logs to have those working...?

**Comment by Anycubic** [comment]
@leofuscaldi please be aware that if you try to add a device right after you switched it on not all of the IDs are recognised, I guess it is due to how zigbee protocol works, same thing like yours happened to me with my TRV valves. I guess each ID value needs to be updated at least once before it can be recognised when adding a device, hope this helps.

**Comment by leofuscaldi** [comment]
> @leofuscaldi please be aware that if you try to add a device right after you switched it on not all of the IDs are recognised, I guess it is due to how zigbee protocol works, same thing like yours happened to me with my TRV valves. I guess each ID value needs to be updated at least once before it can be recognised when adding a device, hope this helps.

Hi @Anycubic, i don't think it's my case. My devices are working for months already, but I've been using Smart life so far....

**Comment by alexualbu** [comment]
@leofuscaldi , i can confirm what @Anycubic says - some devices to not advertise the status for DPs if they have not been touched in a while (i have TRVs same as him, and after a while if the value doesn't change they simply to dot appear in the payload when queried). You can have them appear after you touch them from smartlife or some other way. But don't forget that the DPs are detected when the device is first added in localtuya and saved in HA. You can validate what DPs are advertised by using a third party tool like tuyaapi-cli.
The lights might be a different story - there's a conversation in another issue with the same problem: light switch cannot be controlled. https://github.com/leeyuentuen/localtuya/issues/39#issuecomment-1518709972

**Comment by leofuscaldi** [comment]
For what I could test, I can Read status of almost everything I have on my  Zigbee/Bluetooth Gateway, what I can't is control anything. Tried light (Zigbee) and a fingerbot (Bluetooth) and controling these devices wasn't possible. But for reading all devices, basically I just changed their values (Opened the door for door sensor, tampered the sensor for the Water Leak, forced changing the temperature on the T/H sensors and so on).

Hopefully soon we'll be able to also control lights and other devices.

**Comment by alexualbu** [comment]
@leofuscaldi - so you have tried tuya-cli?

**Comment by caco3** [comment]
I seem to have the same or similar problem.

I got a Water Irrigation Timer (SOP18) from here: https://www.amazon.de/dp/B09P3VRVVB/ref=pe_27091401_487027711_TE_SCE_dp_2

It uses a Wifi Gateway which I successfully added:
![grafik](https://github.com/leeyuentuen/localtuya/assets/1783586/bbed7627-86bc-43e1-88c8-7cee3efbaa4e)

Next thing I tried is to add the Irrigation Timer as a sub device:
![grafik](https://github.com/leeyuentuen/localtuya/assets/1783586/618bc53b-d1d1-40c6-bcee-1d8c99c552d2)

![grafik](https://github.com/leeyuentuen/localtuya/assets/1783586/04bd293a-f2ed-4157-813d-ecc4052510a1)

How ever this fails with the following errors:
![grafik](https://github.com/leeyuentuen/localtuya/assets/1783586/c1577232-ef7c-431f-94e0-7255987cf07d)

```
Logger: custom_components.localtuya.pytuya
Source: custom_components/localtuya/pytuya/__init__.py:325
Integration: LocalTuya integration ([documentation](https://github.com/leeyuentuen/localtuya/), [issues](https://github.com/leeyuentuen/localtuya/issues))
First occurred: 23:26:48 (1 occurrences)
Last logged: 23:26:48
[bf6...4vi] Failed to get status for cid bf166cmaafamcows:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 390, in acquire
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 684, in detect_available_dps
    status = await self.status(cid)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 598, in status
    status = await self.exchange(ACTION_STATUS, cid=cid)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 563, in exchange
    msg = await self.dispatcher.wait_for(seqno)
  File "/config/custom_components/localtuya/pytuya/__init__.py", line 325, in wait_for
    await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError
```

**Comment by Gyosa3** [comment]
Hi I got the data point issue when I was trying to register the sub device with the device ID in the config field "deviceID".

Here is what worked for me: 
- deleted the subdevice.
- set the gateway correctly, with the right protocol (if it was changed for testing)
- action all functions of the subdevice in the Tuya interface, to make sure all possible data points are updated recently.
- REBOOT HA, not just reload Localtuya
- add again the subdevice, using the node_id in the "device_id" configuration field in the UI.

for me it worked, and it found all DPs and even more than advertised by the tuya dev portal !
